from __future__ import annotations

MATERIAL_STANDARDS: list[dict] = [
    {"material_name": "Brick", "property_name": "length", "value": 230, "unit": "mm"},
    {"material_name": "Brick", "property_name": "width", "value": 110, "unit": "mm"},
    {"material_name": "Brick", "property_name": "height", "value": 75, "unit": "mm"},
    {"material_name": "Brick", "property_name": "mortar_gap", "value": 10, "unit": "mm"},
    {"material_name": "Brick", "property_name": "dry_volume_factor", "value": 1.33, "unit": "ratio"},
    {"material_name": "Brick", "property_name": "bricks_per_m3", "value": 500, "unit": "nos"},
    {"material_name": "Cement", "property_name": "bag_weight", "value": 50, "unit": "kg"},
    {"material_name": "Cement", "property_name": "mix_ratio_part_concrete", "value": 1, "unit": "part"},
    {"material_name": "Cement", "property_name": "mix_ratio_part_plaster", "value": 1, "unit": "part"},
    {"material_name": "Cement", "property_name": "density", "value": 1440, "unit": "kg/m3"},
    {"material_name": "Cement", "property_name": "bags_per_m3", "value": 28.8, "unit": "bags"},
    {"material_name": "Steel", "property_name": "density", "value": 7850, "unit": "kg/m3"},
    {"material_name": "Steel", "property_name": "typical_reinforcement_percent", "value": 1.5, "unit": "%"},
    {"material_name": "Steel", "property_name": "weight_per_m3_rcc_min", "value": 80, "unit": "kg"},
    {"material_name": "Steel", "property_name": "weight_per_m3_rcc_max", "value": 120, "unit": "kg"},
    {"material_name": "Sand", "property_name": "bulk_density", "value": 1600, "unit": "kg/m3"},
    {"material_name": "Sand", "property_name": "mix_ratio_part_concrete", "value": 2, "unit": "part"},
    {"material_name": "Sand", "property_name": "mix_ratio_part_plaster", "value": 6, "unit": "part"},
    {"material_name": "Sand", "property_name": "dry_volume_factor", "value": 1.33, "unit": "ratio"},
    {"material_name": "Sand", "property_name": "wastage_min", "value": 5, "unit": "%"},
    {"material_name": "Sand", "property_name": "wastage_max", "value": 10, "unit": "%"},
    {"material_name": "Aggregate", "property_name": "bulk_density", "value": 1450, "unit": "kg/m3"},
    {"material_name": "Aggregate", "property_name": "mix_ratio_part_concrete", "value": 4, "unit": "part"},
    {"material_name": "Aggregate", "property_name": "size", "value": 20, "unit": "mm"},
    {"material_name": "Door", "property_name": "standard_width", "value": 0.9, "unit": "m"},
    {"material_name": "Door", "property_name": "standard_height", "value": 2.1, "unit": "m"},
    {"material_name": "Door", "property_name": "frame_thickness", "value": 0.1, "unit": "m"},
    {"material_name": "Window", "property_name": "standard_width", "value": 1.2, "unit": "m"},
    {"material_name": "Window", "property_name": "standard_height", "value": 1.5, "unit": "m"},
    {"material_name": "Window", "property_name": "sill_height", "value": 0.9, "unit": "m"},
    {"material_name": "Plaster", "property_name": "thickness_internal", "value": 12, "unit": "mm"},
    {"material_name": "Plaster", "property_name": "thickness_external", "value": 15, "unit": "mm"},
    {"material_name": "Concrete", "property_name": "dry_volume_factor", "value": 1.54, "unit": "ratio"},
    {"material_name": "Concrete", "property_name": "mix_ratio_part_cement", "value": 1, "unit": "part"},
    {"material_name": "Concrete", "property_name": "mix_ratio_part_sand", "value": 2, "unit": "part"},
    {"material_name": "Concrete", "property_name": "mix_ratio_part_aggregate", "value": 4, "unit": "part"},
    {"material_name": "Building", "property_name": "floor_height", "value": 3.0, "unit": "m"},
    {"material_name": "Building", "property_name": "wall_thickness", "value": 0.23, "unit": "m"},
    {"material_name": "Building", "property_name": "half_brick_wall", "value": 0.115, "unit": "m"},
    {"material_name": "Building", "property_name": "wastage_factor_min", "value": 5, "unit": "%"},
    {"material_name": "Building", "property_name": "wastage_factor_max", "value": 10, "unit": "%"},
]
