"""create_material_standards

Revision ID: 7906f18722c6
Revises: b6b17a6b0da0
Create Date: 2026-03-26 09:55:39.707292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7906f18722c6'
down_revision: Union[str, Sequence[str], None] = 'b6b17a6b0da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_standards',
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(length=50), nullable=True),
    sa.Column('property_name', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('default', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('standard_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_standards')
    # ### end Alembic commands ###
