"""create_plans

Revision ID: 8cdf4d150443
Revises: 4a26aa56c8bf
Create Date: 2026-03-26 09:51:19.052465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cdf4d150443'
down_revision: Union[str, Sequence[str], None] = '4a26aa56c8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('unit_system', sa.String(length=10), nullable=True),
    sa.Column('scale_type', sa.String(length=20), nullable=True),
    sa.Column('scale_ratio', sa.Float(), nullable=True),
    sa.Column('scale_factor', sa.Double(), nullable=True),
    sa.Column('dpi', sa.Float(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('current_page', sa.Integer(), nullable=True),
    sa.Column('page_scale_factor', sa.Double(), nullable=True),
    sa.Column('detected_units', sa.String(length=20), nullable=True),
    sa.Column('blueprint_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('processing_progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('upload_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index('ix_plans_user_id', 'plans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plans_user_id', table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
