"""create_plan_calibrations

Revision ID: 99044ae324e0
Revises: 8cdf4d150443
Create Date: 2026-03-26 09:51:32.130297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99044ae324e0'
down_revision: Union[str, Sequence[str], None] = '8cdf4d150443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_calibrations',
    sa.Column('calibration_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('pixel_length', sa.Float(), nullable=True),
    sa.Column('real_length', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('scale_factor', sa.Double(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('calibration_id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_index('ix_plan_calibrations_plan_id', 'plan_calibrations', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plan_calibrations_plan_id', table_name='plan_calibrations')
    op.drop_table('plan_calibrations')
    # ### end Alembic commands ###
