"""create_material_estimates

Revision ID: b6b17a6b0da0
Revises: edb43bf8fff0
Create Date: 2026-03-26 09:55:34.206177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b17a6b0da0'
down_revision: Union[str, Sequence[str], None] = 'edb43bf8fff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_estimates',
    sa.Column('estimate_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('bricks_count', sa.Integer(), nullable=True),
    sa.Column('cement_bags', sa.Float(), nullable=True),
    sa.Column('steel_kg', sa.Float(), nullable=True),
    sa.Column('sand_kg', sa.Float(), nullable=True),
    sa.Column('doors_count', sa.Integer(), nullable=True),
    sa.Column('windows_count', sa.Integer(), nullable=True),
    sa.Column('total_area', sa.Float(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('estimate_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('estimate_id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_index('ix_material_estimates_plan_id', 'material_estimates', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_material_estimates_plan_id', table_name='material_estimates')
    op.drop_table('material_estimates')
    # ### end Alembic commands ###
