"""create_elements

Revision ID: edb43bf8fff0
Revises: 94cb6141ac54
Create Date: 2026-03-26 09:55:28.215548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edb43bf8fff0'
down_revision: Union[str, Sequence[str], None] = '94cb6141ac54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elements',
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=True),
    sa.Column('element_type', sa.String(length=50), nullable=False),
    sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pixel_length', sa.Float(), nullable=True),
    sa.Column('pixel_area', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('thickness', sa.Float(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('detected_label', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.floor_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('element_id')
    )
    op.create_index('ix_elements_floor_id', 'elements', ['floor_id'], unique=False)
    op.create_index('ix_elements_plan_id', 'elements', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_elements_plan_id', table_name='elements')
    op.drop_index('ix_elements_floor_id', table_name='elements')
    op.drop_table('elements')
    # ### end Alembic commands ###
